# ship attack status codes
ATTACK_UNSUCCESSFUL = 0
SHIP_HIT = 1
SHIP_SUNK = 2

# ship sizes
CARRIER_LENGTH = 5
BATTLESHIP_LENGTH = 4
CRUISER_LENGTH = 3
PATROL_SHIP_LENGTH = 2
SHIP_LENGTHS = {
    "Carrier": CARRIER_LENGTH,
    "Battleship": BATTLESHIP_LENGTH,
    "Cruiser": CARRIER_LENGTH,
    "PatrolShip": PATROL_SHIP_LENGTH,
}
